"""pages blocks seo versions

Revision ID: 1b630ca0a483
Revises: cf5c5c45d5ec
Create Date: 2026-07-20 15:46:19.792965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b630ca0a483'
down_revision: Union[str, None] = 'cf5c5c45d5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_definition',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('seo_meta',
    sa.Column('seo_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('canonical_url', sa.String(length=500), nullable=True),
    sa.Column('og_title', sa.String(length=255), nullable=True),
    sa.Column('og_description', sa.String(length=500), nullable=True),
    sa.Column('og_image_media_id', sa.UUID(), nullable=True),
    sa.Column('twitter_card_type', sa.String(length=50), nullable=True),
    sa.Column('robots', sa.String(length=100), nullable=True),
    sa.Column('schema_jsonld', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_version',
    sa.Column('entity_type', sa.Enum('PAGE', 'BLOG_POST', 'SETTINGS', name='entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('change_note', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_version_entity_id'), 'entity_version', ['entity_id'], unique=False)
    op.create_table('page',
    sa.Column('page_type', sa.Enum('HOME', 'ABOUT', 'PROJECTS', 'BLOG', 'CONTACT', name='page_type'), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'UNPUBLISHED', name='page_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('featured_image_media_id', sa.UUID(), nullable=True),
    sa.Column('seo_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seo_id'], ['seo_meta.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page_type'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('page_block',
    sa.Column('page_id', sa.UUID(), nullable=False),
    sa.Column('block_definition_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_definition_id'], ['block_definition.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('page_block')
    op.drop_table('page')
    op.drop_index(op.f('ix_entity_version_entity_id'), table_name='entity_version')
    op.drop_table('entity_version')
    op.drop_table('seo_meta')
    op.drop_table('block_definition')
    # ### end Alembic commands ###
