"""media library

Revision ID: 23f9c7fca2a1
Revises: 1b630ca0a483
Create Date: 2026-07-20 16:46:04.245571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f9c7fca2a1'
down_revision: Union[str, None] = '1b630ca0a483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_folder',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_folder_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_folder_id'], ['media_folder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_key', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.String(length=500), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['media_folder.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_key')
    )
    op.create_table('media_usage',
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PAGE', 'BLOG_POST', 'PROPERTY', 'MENU', 'SETTINGS', name='media_usage_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_usage_entity_id'), 'media_usage', ['entity_id'], unique=False)
    op.create_index(op.f('ix_media_usage_media_id'), 'media_usage', ['media_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_usage_media_id'), table_name='media_usage')
    op.drop_index(op.f('ix_media_usage_entity_id'), table_name='media_usage')
    op.drop_table('media_usage')
    op.drop_table('media')
    op.drop_table('media_folder')
    # ### end Alembic commands ###
