"""add sort_order to property

Revision ID: 826f944e1e19
Revises: e5f31812b720
Create Date: 2026-08-04 11:35:19.259419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '826f944e1e19'
down_revision: Union[str, None] = 'e5f31812b720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('sort_order', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'sort_order')
    # ### end Alembic commands ###
