"""add visitor contact fields to chat conversation

Revision ID: 8b0d8f2022fc
Revises: da194840ca80
Create Date: 2026-07-31 13:53:00.994050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0d8f2022fc'
down_revision: Union[str, None] = 'da194840ca80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_conversation', sa.Column('visitor_name', sa.String(length=120), nullable=True))
    op.add_column('chat_conversation', sa.Column('visitor_email', sa.String(length=255), nullable=True))
    op.add_column('chat_conversation', sa.Column('visitor_phone', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_conversation', 'visitor_phone')
    op.drop_column('chat_conversation', 'visitor_email')
    op.drop_column('chat_conversation', 'visitor_name')
    # ### end Alembic commands ###
