"""blog and properties

Revision ID: 8ce3ac741d38
Revises: 23f9c7fca2a1
Create Date: 2026-07-22 11:47:44.621032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce3ac741d38'
down_revision: Union[str, None] = '23f9c7fca2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('applies_to', sa.Enum('BLOG', 'PROPERTY', 'BOTH', name='category_applies_to'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('property',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=150), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('price_display', sa.String(length=100), nullable=True),
    sa.Column('price_value', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_bracket', sa.Enum('UNDER_2', 'RANGE_2_TO_5', 'RANGE_5_TO_10', 'OVER_10', name='budget_bracket'), nullable=True),
    sa.Column('spec_a', sa.String(length=100), nullable=True),
    sa.Column('spec_b', sa.String(length=100), nullable=True),
    sa.Column('area_sqft', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('beds_options', sa.JSON(), nullable=True),
    sa.Column('tag_text', sa.String(length=50), nullable=True),
    sa.Column('status_text', sa.String(length=50), nullable=True),
    sa.Column('is_signature', sa.Boolean(), nullable=False),
    sa.Column('featured_image_media_id', sa.UUID(), nullable=True),
    sa.Column('seo_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='property_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['seo_id'], ['seo_meta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('blog_post',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('featured_image_media_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', name='blog_post_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('seo_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seo_id'], ['seo_meta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('property_category',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id', 'category_id')
    )
    op.create_table('blog_post_category',
    sa.Column('blog_post_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_post_id', 'category_id')
    )
    op.create_table('blog_post_tag',
    sa.Column('blog_post_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blog_post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_post_id', 'tag_id')
    )
    op.create_table('property_media',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property_media')
    op.drop_table('blog_post_tag')
    op.drop_table('blog_post_category')
    op.drop_table('property_category')
    op.drop_table('blog_post')
    op.drop_table('property')
    op.drop_table('tag')
    op.drop_table('category')
    # ### end Alembic commands ###
