"""map management tables

Revision ID: cda6c533e258
Revises: 37f099b8a6a6
Create Date: 2026-07-29 15:41:36.538851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cda6c533e258'
down_revision: Union[str, None] = '37f099b8a6a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_project',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('map_provider_type', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_provider_config',
    sa.Column('provider_type', sa.String(length=20), nullable=False),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('tile_url', sa.String(length=500), nullable=True),
    sa.Column('style_url', sa.String(length=500), nullable=True),
    sa.Column('attribution', sa.String(length=500), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_type')
    )
    op.create_table('map_layer',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('stroke_color', sa.String(length=20), nullable=False),
    sa.Column('fill_color', sa.String(length=20), nullable=False),
    sa.Column('fill_opacity', sa.Float(), nullable=False),
    sa.Column('stroke_weight', sa.Integer(), nullable=False),
    sa.Column('default_visible', sa.Boolean(), nullable=False),
    sa.Column('color_rules', sa.JSON(), nullable=True),
    sa.Column('label_property', sa.String(length=255), nullable=True),
    sa.Column('popup_enabled', sa.Boolean(), nullable=False),
    sa.Column('popup_properties', sa.JSON(), nullable=True),
    sa.Column('stroke_style', sa.String(length=10), nullable=False),
    sa.Column('geojson', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['map_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_share_link',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_views', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['map_project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_index(op.f('ix_map_share_link_token'), 'map_share_link', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_map_share_link_token'), table_name='map_share_link')
    op.drop_table('map_share_link')
    op.drop_table('map_layer')
    op.drop_table('map_provider_config')
    op.drop_table('map_project')
    # ### end Alembic commands ###
