"""add brochure_media_id to property

Revision ID: e5f31812b720
Revises: 02e9f5a2bc33
Create Date: 2026-08-01 15:14:21.713772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f31812b720'
down_revision: Union[str, None] = '02e9f5a2bc33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('brochure_media_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'brochure_media_id')
    # ### end Alembic commands ###
