"""Add map_project_id to property

Revision ID: e6c368d21142
Revises: cda6c533e258
Create Date: 2026-07-29 17:54:23.463504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c368d21142'
down_revision: Union[str, None] = 'cda6c533e258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('map_project_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'property', 'map_project', ['map_project_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('redirect_rules_from_path_key'), 'redirect_rules', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('redirect_rules_from_path_key'), 'redirect_rules', ['from_path'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'property', type_='foreignkey')
    op.drop_column('property', 'map_project_id')
    # ### end Alembic commands ###
