import uuid
from typing import Protocol

from app.models.category import Category


class CategoryRepository(Protocol):
    async def get_by_id(self, category_id: uuid.UUID) -> Category | None: ...
    async def list_by_ids(self, category_ids: list[uuid.UUID]) -> list[Category]: ...
    async def list_all(self, applies_to: str | None = None) -> list[Category]: ...
    async def create(self, category: Category) -> Category: ...
    async def update(self, category: Category) -> Category: ...
    async def delete(self, category: Category) -> None: ...
    async def count_usage(self, category_id: uuid.UUID) -> int: ...
