import uuid
from typing import Protocol

from app.models.entity_version import EntityType, EntityVersion


class EntityVersionRepository(Protocol):
    async def create(self, version: EntityVersion) -> EntityVersion: ...
    async def list_for_entity(self, entity_type: EntityType, entity_id: uuid.UUID) -> list[EntityVersion]: ...
    async def get_by_id(self, version_id: uuid.UUID) -> EntityVersion | None: ...
    async def next_version_number(self, entity_type: EntityType, entity_id: uuid.UUID) -> int: ...
