import uuid
from typing import Protocol

from app.models.form_submission import FormSubmission


class FormSubmissionRepository(Protocol):
    async def get_by_id(self, submission_id: uuid.UUID) -> FormSubmission | None: ...

    async def list(
        self, *, page: int, per_page: int, form_key: str | None = None, status: str | None = None
    ) -> tuple[list[FormSubmission], int]: ...

    async def list_all_matching(self, *, form_key: str | None, status: str | None) -> list[FormSubmission]: ...
    async def create(self, submission: FormSubmission) -> FormSubmission: ...
    async def update(self, submission: FormSubmission) -> FormSubmission: ...
    async def delete(self, submission: FormSubmission) -> None: ...
