import uuid
from typing import Protocol

from app.models.map_layer import MapLayer
from app.models.map_project import MapProject
from app.models.map_provider_config import MapProviderConfig
from app.models.map_share_link import MapShareLink


class MappingRepository(Protocol):
    async def list_projects(self) -> list[MapProject]: ...
    async def get_project(self, project_id: uuid.UUID) -> MapProject | None: ...
    async def create_project(self, project: MapProject) -> MapProject: ...
    async def update_project(self, project: MapProject) -> MapProject: ...
    async def delete_project(self, project: MapProject) -> None: ...

    async def list_layers(self, project_id: uuid.UUID | None = None) -> list[MapLayer]: ...
    async def get_layer(self, layer_id: uuid.UUID) -> MapLayer | None: ...
    async def create_layer(self, layer: MapLayer) -> MapLayer: ...
    async def update_layer(self, layer: MapLayer) -> MapLayer: ...
    async def delete_layer(self, layer: MapLayer) -> None: ...

    async def get_share_link_by_project(self, project_id: uuid.UUID) -> MapShareLink | None: ...
    async def get_share_link_by_token(self, token: str) -> MapShareLink | None: ...
    async def create_share_link(self, link: MapShareLink) -> MapShareLink: ...
    async def update_share_link(self, link: MapShareLink) -> MapShareLink: ...

    async def list_providers(self) -> list[MapProviderConfig]: ...
    async def get_provider(self, provider_type: str) -> MapProviderConfig | None: ...
    async def create_provider(self, config: MapProviderConfig) -> MapProviderConfig: ...
    async def update_provider(self, config: MapProviderConfig) -> MapProviderConfig: ...
    async def delete_provider(self, config: MapProviderConfig) -> None: ...
