import uuid
from typing import Protocol

from app.models.media_folder import MediaFolder


class MediaFolderRepository(Protocol):
    async def get_by_id(self, folder_id: uuid.UUID) -> MediaFolder | None: ...
    async def list_all(self) -> list[MediaFolder]: ...
    async def create(self, folder: MediaFolder) -> MediaFolder: ...
    async def update(self, folder: MediaFolder) -> MediaFolder: ...
    async def delete(self, folder: MediaFolder) -> None: ...
    async def count_children(self, folder_id: uuid.UUID) -> int: ...
