import uuid
from typing import Protocol

from app.models.media import Media


class MediaRepository(Protocol):
    async def get_by_id(self, media_id: uuid.UUID, include_deleted: bool = False) -> Media | None: ...

    async def list(
        self,
        *,
        page: int,
        per_page: int,
        folder_id: uuid.UUID | None = None,
        mime_type: str | None = None,
        search: str | None = None,
    ) -> tuple[list[Media], int]: ...

    async def list_trash(self, *, page: int, per_page: int) -> tuple[list[Media], int]: ...
    async def create(self, media: Media) -> Media: ...
    async def create_many(self, media_items: list[Media]) -> list[Media]: ...
    async def update(self, media: Media) -> Media: ...
    async def soft_delete(self, media: Media) -> None: ...
    async def restore(self, media: Media) -> None: ...
    async def count_in_folder(self, folder_id: uuid.UUID) -> int: ...
