import uuid
from typing import Protocol

from app.models.menu import Menu, MenuItem


class MenuRepository(Protocol):
    async def get_by_key(self, key: str) -> Menu | None: ...
    async def list_all(self) -> list[Menu]: ...
    async def list_items(self, menu_id: uuid.UUID) -> list[MenuItem]: ...
    async def delete_all_items(self, menu_id: uuid.UUID) -> None: ...
    async def create_item(self, item: MenuItem) -> MenuItem: ...
