import uuid
from typing import Protocol

from app.models.notification import Notification


class NotificationRepository(Protocol):
    async def create(self, notification: Notification) -> Notification: ...
    async def create_many(self, notifications: list[Notification]) -> list[Notification]: ...
    async def get_by_id(self, notification_id: uuid.UUID) -> Notification | None: ...

    async def list_for_user(
        self, user_id: uuid.UUID, *, page: int, per_page: int, unread_only: bool = False
    ) -> tuple[list[Notification], int]: ...

    async def unread_count(self, user_id: uuid.UUID) -> int: ...
    async def mark_read(self, notification: Notification) -> Notification: ...
    async def mark_all_read(self, user_id: uuid.UUID) -> None: ...
