import uuid
from typing import Protocol

from app.models.page import Page, PageType
from app.models.page_block import PageBlock


class PageRepository(Protocol):
    async def get_by_type(self, page_type: PageType) -> Page | None: ...
    async def list_all(self) -> list[Page]: ...
    async def update(self, page: Page) -> Page: ...
    async def get_block(self, block_id: uuid.UUID) -> PageBlock | None: ...
    async def add_block(self, block: PageBlock) -> PageBlock: ...
    async def update_block(self, block: PageBlock) -> PageBlock: ...
    async def delete_block(self, block: PageBlock) -> None: ...
    async def reorder_blocks(self, page_id: uuid.UUID, ordered_block_ids: list[uuid.UUID]) -> None: ...
    async def max_block_position(self, page_id: uuid.UUID) -> int: ...
    async def upsert_seo(self, page: Page, seo_data: dict) -> Page: ...
