import uuid
from typing import Protocol

from app.models.property import Property


class PropertyRepository(Protocol):
    async def get_by_id(self, property_id: uuid.UUID, include_deleted: bool = False) -> Property | None: ...

    async def get_by_slug(self, slug: str) -> Property | None: ...

    async def list(
        self,
        *,
        page: int,
        per_page: int,
        status: str | None = None,
        city: str | None = None,
        category_id: uuid.UUID | None = None,
        budget_bracket: str | None = None,
        search: str | None = None,
        is_signature: bool | None = None,
    ) -> tuple[list[Property], int]: ...

    async def list_trash(self, *, page: int, per_page: int) -> tuple[list[Property], int]: ...
    async def reorder(self, ordered_ids: list[uuid.UUID]) -> None: ...
    async def create(self, property_: Property) -> Property: ...
    async def update(self, property_: Property) -> Property: ...
    async def upsert_seo(self, property_: Property, seo_data: dict) -> Property: ...
    async def set_gallery(self, property_id: uuid.UUID, media_ids: list[uuid.UUID]) -> Property: ...
    async def soft_delete(self, property_: Property) -> None: ...
    async def restore(self, property_: Property) -> None: ...
