import uuid
from typing import Protocol

from app.models.refresh_token import RefreshToken


class RefreshTokenRepository(Protocol):
    async def create(self, token: RefreshToken) -> RefreshToken: ...
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke(self, token: RefreshToken) -> None: ...
    async def revoke_all_for_user(self, user_id: uuid.UUID) -> None: ...
