import uuid
from typing import Protocol

from app.models.role import Role


class RoleRepository(Protocol):
    async def get_by_id(self, role_id: uuid.UUID) -> Role | None: ...
    async def get_by_name(self, name: str) -> Role | None: ...
    async def list(self) -> list[Role]: ...
    async def create(self, role: Role) -> Role: ...
    async def update(self, role: Role) -> Role: ...
    async def delete(self, role: Role) -> None: ...
