import uuid
from typing import Protocol

from app.models.tag import Tag


class TagRepository(Protocol):
    async def get_by_id(self, tag_id: uuid.UUID) -> Tag | None: ...
    async def list_by_ids(self, tag_ids: list[uuid.UUID]) -> list[Tag]: ...
    async def list_all(self) -> list[Tag]: ...
    async def create(self, tag: Tag) -> Tag: ...
    async def update(self, tag: Tag) -> Tag: ...
    async def delete(self, tag: Tag) -> None: ...
    async def count_usage(self, tag_id: uuid.UUID) -> int: ...
