import uuid
from typing import Protocol

from app.models.user import User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: uuid.UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def list(
        self, *, page: int, per_page: int, search: str | None = None
    ) -> tuple[list[User], int]: ...

    async def list_by_permission(self, permission_key: str) -> list[User]: ...
    async def create(self, user: User) -> User: ...
    async def update(self, user: User) -> User: ...
    async def soft_delete(self, user: User) -> None: ...
    async def restore(self, user: User) -> None: ...
