import type {
  AccordionConfig,
  ContactFormConfig,
  CtaConfig,
  DividerConfig,
  FaqConfig,
  FeaturesConfig,
  GalleryConfig,
  HeroBannerConfig,
  ImageConfig,
  MapConfig,
  PricingConfig,
  SpacerConfig,
  StatisticsConfig,
  TeamConfig,
  TestimonialsConfig,
  TextConfig,
  TimelineConfig,
  VideoConfig,
} from "@/types/blockConfigs";

export const DEFAULT_CONFIGS: Record<string, Record<string, unknown>> = {
  hero_banner: {
    button_label: "",
    button_href: "",
    slides: [],
  } satisfies HeroBannerConfig,
  text: { heading: "", body: "" } satisfies TextConfig,
  image: { image_url: "", alt_text: "", caption: "" } satisfies ImageConfig,
  gallery: { heading: "", images: [] } satisfies GalleryConfig,
  video: { heading: "", video_url: "", poster_image_url: "" } satisfies VideoConfig,
  faq: { heading: "", items: [] } satisfies FaqConfig,
  testimonials: { heading: "", items: [] } satisfies TestimonialsConfig,
  features: { heading: "", items: [] } satisfies FeaturesConfig,
  pricing: { heading: "", plans: [] } satisfies PricingConfig,
  team: { heading: "", members: [] } satisfies TeamConfig,
  timeline: { heading: "", items: [] } satisfies TimelineConfig,
  map: { heading: "", address: "", embed_url: "" } satisfies MapConfig,
  accordion: { heading: "", items: [] } satisfies AccordionConfig,
  statistics: { heading: "", items: [] } satisfies StatisticsConfig,
  contact_form: { heading: "", description: "", form_key: "contact_callback" } satisfies ContactFormConfig,
  cta: { heading: "", description: "", button_label: "", button_href: "" } satisfies CtaConfig,
  spacer: { height_px: 48 } satisfies SpacerConfig,
  divider: { style: "solid" } satisfies DividerConfig,
};
